project:
  type: website

website:
  title: "Blue Pulse💧"
  navbar:


    right: 
      - href: index.qmd
        text: Overview
    
    
        
      - text: "Prototype"
        menu:
        - text: "Geospatial Data Analysis_P1"
          href: "Prototype/Geospatial Data Analysis_P1.html"
        - text: "Geospatial Data Analysis_P2"
          href: "Prototype/Geospatial Data Analysis_P2.html"
        - text: "WASH-Based Health Trend Analysis"
          href: "Prototype/Forcasting.html"
        - text: "Comfirmatory Data Analysis(CDA)"
          href: "Prototype/CDA.html"
        - text: "Story Board"
        
        
        
      - text: "Shiny App"
        menu: 
          - text: "Shiny App"
            href: "https://liyml.shinyapps.io/BluePulse/"
          - text: "User guide"
      
      
      
      
      - text: "Project Poster" 

      


      - text: "Team"
        menu:
        - text: "About this project"
          href: about.qmd
        - text: "Meeting Minutes"
          href: "MeetingMinutes.html"
        - text: "Proposal" 
          href: "Proposal.html"
        


format:
  html:
    css: 
    - styles.css 
    - box.css
    theme: darkly
    toc: true

editor: visual


