project:
  type: website

website:
  title: "Blue Pulse💧"
  navbar:


    right: 
      - href: index.qmd
        text: Overview
    
    
        
      - text: "Prototype"
        menu:
        - text: "Geospatial Data Analysis"
        - text: "WASH-Based Health Trend Analysis"
          href: "Prototype/Forcasting.html"
        - text: "Comfirmatory Data Analysis(CDA)"
        - text: "Story Board"
        
        
        
      - text: "Shiny App"
        menu: 
          - text: "Shiny App"
          - text: "User guide"
      
      
      
      
      - text: "Project Poster" 

      


      - text: "Team"
        menu:
        - text: "About this project"
          href: about.qmd
        - text: "Meeting Minutes"
          href: "MeetingMinutes.html"
        - text: "Proposal" 
          href: "Proposal.html"
        


format:
  html:
    css: styles.css  # Reference external CSS file
    theme: darkly
    toc: true

editor: visual


