project:
  type: website

website:
  title: "ISSS608_VAA_GroupProject_T9"
  navbar:
    left:
    - text: "Proposal"
      menu:
        - text: "Proposal"
          href: "Proposal.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
 
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

