project:
  type: website

website:
  title: "Blue Pulse💧"
  navbar:


    right: 
      - href: index.qmd
        text: Overview
      - href: "Proposal.html"
        text: "Proposal"
      - href: "MeetingMinutes.html"
        text: "Meeting Minutes"
      - text: "Team"
        menu:
        - text: "About this project"
          href: about.qmd
        - text: "Meeting Minutes"
          href: "MeetingMinutes.html"


format:
  html:
    css: styles.css  # Reference external CSS file
    theme: darkly
    toc: true

editor: visual


